name: tox

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - python: '3.7'
            toxenv: py37
            os: ubuntu-latest
          - python: '3.8'
            toxenv: py38
            os: ubuntu-latest
          - python: '3.9'
            toxenv: py39
            os: ubuntu-latest
          - python: '3.10'
            toxenv: py310
            os: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup python${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"

      - name: Install tox
        run: python -m pip install tox

      - name: Prepare tox env
        run: tox --notest
        env:
          TOXENV: ${{ matrix.toxenv }}

      - name: Run tox
        run: tox
        env:
          COVERALLS_PARALLEL: 'true'
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: yes
          TOXENV: ${{ matrix.toxenv }}
