name: tox

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  mypy:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Setup python3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install poetry
        run: python -m pip install poetry

      - run: poetry install

      - name: mypy
        run: poetry run mypy
        env:
          FORCE_COLOR: 1

  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        python:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'

    steps:
      - uses: actions/checkout@v2

      - name: Setup python${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"

      - name: Install poetry
        run: python -m pip install poetry

      - run: poetry install

      - name: pytest
        run: poetry run pytest -vv
        env:
          COVERALLS_PARALLEL: 'true'
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: 1
